### ISSUE TITLE
Source code for barrier certificate

### ISSUE THREAD

**Issue by gy2256** [GT-STAR-Lab/MARBLER#14]
Hello, 

Thanks for the great work! I have a question about the barrier certificate. 

Could you show me where is the source code located for the different barrier certificates?
More specifically, where are these defined: [https://github.com/GT-STAR-Lab/MARBLER/blob/0f6046b5a076cf5adb0987c40bec3f9acb4733c5/robotarium_gym/utilities/controller.py#L1-L2](https://github.com/GT-STAR-Lab/MARBLER/blob/0f6046b5a076cf5adb0987c40bec3f9acb4733c5/robotarium_gym/utilities/controller.py#L1-L2)

**Comment by Yuxin916** [comment]
hi you need to Download and Install the [Robotarium Python Simulator](https://github.com/robotarium/robotarium_python_simulator) by git clone the repo.

**Comment by gy2256** [comment]
Thanks!
